parameters:
  - name: dependsOn
    type: object
    default: []

stages:
  - stage: DeleteAWSCLIv1
    displayName: Delete AWS CLI v1
    dependsOn: ${{ parameters.dependsOn }}
    jobs:
      - job: DeleteAWS
        continueOnError: true
        workspace:
          clean: all
        displayName: Delete AWS CLI v1
        
        steps:
        - task: Bash@3
          name: UninstallAWS
          displayName: Uninstall AWC CLI v1
          inputs:
            targetType: inline
            script: |
              sudo rm -rf /usr/local/aws
              sudo rm -rf /usr/local/bin/aws*