parameters:
  - name: stageName
    type: string
    default: ''

  - name: installAWS
    type: boolean
    default: false

  - name: arch
    type: string
    default: ''

  - name: regionName
    type: string
    default: 'us-east-1'
    
  - name: awsCredentials
    type: string
    default: ''

stages:
  - stage: ${{ parameters.stageName }}
    displayName: Install AWS CLI v1
    jobs:

      - ${{ if eq(parameters.installAWS, true) }}:
        - job: InstallAWS
          displayName: Install AWS and check identity
          steps:
            - task: Bash@3
              name: CheckIfInstalled
              displayName: Check if AWS CLI is installed already
              inputs:
                targetType: inline
                script: |
                  if command -v aws >/dev/null 2>&1; then
                    echo "AWS CLI found"
                    echo "##vso[task.setvariable variable=installed;isOutput=true]true"
                  else
                    echo "AWS CLI NOT found"
                    echo "##vso[task.setvariable variable=installed;isOutput=true]false"
                  fi

            - task: Bash@3
              name: InstallAWSCLIv1
              displayName: Install AWS CLI v1
              condition: eq($(CheckifInstalled.installed), 'false')
              inputs:
                targetType: inline
                script: |
                  curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
                  unzip awscli-bundle.zip
                  sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
                  rm -r awscli-bundle*

            - task: Bash@3
              name: CheckAWSCLIVersion
              condition: eq($(CheckIfInstalled.installed), 'true')
              displayName: Check AWS CLI installed version
              inputs:
                targetType: inline
                script: aws --version

                
        # - job: GetCallerIdentity
          # displayName: Get caller identity
          # dependsOn: 
            # - InstallAWS
          # steps:
            # - checkout: none
            # - task: AWSCLI@1
              # name: GetCallerIdentity
              # displayName: Running aws sts get-caller-identity
              # inputs:
                # awsCredentials: ${{ parameters.awsCredentials }}
                # regionName: ${{ parameters.regionName }}
                # awsCommand: 'sts'
                # awsSubCommand: 'get-caller-identity'
              
              
      - ${{ if ne(parameters.installAWS, true) }}:
        - job: SkippingAWSInstall
          displayName: Skipping AWS installation
          steps:
            - script: |
                echo "Already installed:"
                aws --version
