name: 'infra-$(Date:yyyyMMdd)$(Rev:.r)'

trigger:
  branches:
    include:
      - azure-pipeline

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_VERSION: "1.11.4"
  TF_WORKING_DIR: "terraform/azure-app-service"

stages:
  - stage: Terraform_infra
    displayName: "Terraform infrastucture provisioning"
    condition: 

    jobs:
    - job: Terraform_Init
      displayName: "Terraform Init and Apply"
      steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: "$(TF_VERSION)"
          displayName: "Install Terraform v$(TF_VERSION)"
        
        - task: TerraformTaskV3@3
          inputs:
            command: "validate"
          displayName: 

