name: 'infra-$(Date:yyyyMMdd)$(Rev:.r)'

trigger:
  branches:
    include:
      - azure-pipeline

pool:
  name: Local

variables:
  TF_VERSION: "1.11.4"
  TF_WORKING_DIR: "terraform/azure-app-service"

stages:
  - stage: Terraform_infra
    displayName: "Terraform infrastucture provisioning"
    condition: 

    jobs:
    - job: Terraform_Apply
      displayName: "Terraform Init and Apply"
      steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: "$(TF_VERSION)"
          displayName: "Install Terraform v$(TF_VERSION)"
        
        - script: |
            terraform plan
          name: TerraformPlan
          workingDirectory: "$(TF_WORKING_DIR)"
          displayName: "Plan Terraform"
        
        - script: |
            echo "++++++ WOULD RUN: terraform apply --auto-approve ++++++"
          name: TerraformApply
          condition: succeeded("TerraformPlan")
          workingDirectory: "$(TF_WORKING_DIR)"
          displayName: "Apply Terraform"

