global:
  domain: argocd.mishap.local

configs:
  params:
    server.insecure: true

projects:
  enabled: true
 
dex:
  enabled: false

controller:
  extraArgs:
    - --application-namespaces
    - "*"
server:
  extraArgs:
    - --insecure
    - --application-namespaces
    - "*"
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
