parameters:
  - name: dependsOn
    type: object
    default: []

jobs:
  - job: 'deleteAWS'
    workspace:
      clean: all
    displayName: Delete AWS CLI v1
    dependsOn: ${{ parameters.dependsOn }}
    steps:
    - task: Bash@3
      displayName: Uninstall AWC CLI v1
      inputs:
        targetType: inline
        script: |
          sudo rm -rf /usr/local/aws
          sudo rm -rf /usr/local/bin/aws*