global:
  scrape_interval: 1s
  evaluation_interval: 1s

rule_files:
  - prometheus.rules.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ "prometheus:9090" ]
        labels:
          group: "internal_monitoring"
  
  - job_name: node_exporter
    static_configs:
      - targets: [ "node_exporter:9100" ]
        labels:
          group: "internal_monitoring"

  - job_name: local-business
    static_configs:
      - targets: [ "local-business:5400" ]
        labels:
          group: "app"
  
  - job_name: grafana
    scrape_interval: 5s
    static_configs:
      - targets: [ "grafana:3000" ]
        labels:
          group: "internal_monitoring"
    
