global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - prometheus.rules.yml

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets: [ "localhost:9090" ]

  - job_name: docker
    static_configs:
      - targets: [ "localhost:9323" ]

  - job_name: local-business
    scrape_interval: 3s
    static_configs:
      - targets: [ "localhost:5400" ]
        labels:
          group: "local"
