queries:
  - name: local_http_request_rate
    description: Local Business's rate of incoming HTTP requests within 5m interval
    tags: [rate, http, total]
    units: requests/second
    interval: 5m
    query: rate(local_http_requests_total[5m])

  - name: local_http_200_success_rate
    description: Local Business's rate of incoming successful HTTP requests (status=200) within 5m interval
    tags: [rate, http, total, success]
    units: requests/second
    interval: 5m
    query: rate(local_http_requests_total{status_code="200"}[5m])

  - name: local_http_5xx_error_rate
    description: Local Business's rate of incoming successful HTTP requests (status=200) within 5m interval
    tags: [rate, http, total, error]
    units: errors/second
    interval: 5m
    query: rate(local_http_requests_total{status_code=~"5.."}[1m])

  - name: local_request_latency
    description: Local Businesss requests latency for a 95th percentile within 5m interval
    tags: [latency, http]
    units: seconds
    interval: 1m
    query: histogram_quantile(0.95, rate(local_http_request_duration_seconds_bucket[5m]))

  - name: local_http_5xx_error_rate_graph
    description: ""
    tags: [rate, http, error]
    interval: 5m
    query: sum(rate(local_http_requests_total{status=~"5.."}[5m])) / sum(rate(local_http_requests_total[5m]))