parameters:
  - name: stageName
    type: string

  - name: dependsOn
    type: object
    default: []

  - name: environment
    type: string

  - name: manifests
    type: object
    default: []

stages:
  - stage: Deploy
    displayName: Deploy k8s ${{ parameters.manifests.name }}
    dependsOn: ${{ parameters.dependsOn }}
    jobs:
      - deployment: Deployment
        displayName: Deployment
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
               - checkout: self

               - ${{ each item in parameters.manifests }}:
                 - task: Bash@3
                   name: ${{ format('Install{0}', item.name) }}
                   displayName: Install ${{ item.name }} provided manifests
                   inputs:
                     targetType: inline
                     script: |
                       kubectl apply -f ${{ item.manifest }}
        workspace:
          clean: all