parameters:
  - name: stageName
    type: string

  - name: dependsOn
    type: object
    default: []

  - name: environment
    type: string

  - name: manifests
    type: object
    default: []

stages:
  - stage: Deploy
    displayName: Deploy k8s ${{ parameters.manifest.name }}
    dependsOn: ${{ parameters.dependsOn }}
    jobs:
       - deployment: Deployment
         displayName: Deployment
         environment: ${{ parameters.environment }}
         strategy:
           runOnce:
             deploy:
               steps:
                checkout: self
                
                - ${{ each item in parameters.manifests }}:
                  - task: KubernetesManifest@1
                    displayName: "Apply ${{ item.name }}"
                    inputs:
                      action: deploy
                      kubernetesServiceConnection: $(kubernetesServiceConnection)
                      namespace: nginx
                      manifests: |
                        ${{ item.manifest }}
