parameters:
  - name: stageName
    type: string

  - name: dependsOn
    type: object
    default: []

  - name: environment
    type: string

  - name: regionName
    type: string

  - name: awsCredentials
    type: string

  - name: manifests
    type: object
    default: []

stages:
  - stage: Deploy
    displayName: Deploy k8s ${{ parameters.manifests.name }}
    dependsOn: ${{ parameters.dependsOn }}
    jobs:
      - job: GetCallerIdentity
        displayName: Get caller identity
        steps:
          - checkout: none
          - task: AWSCLI@1
            name: GetCallerIdentity
            displayName: Running aws sts get-caller-identity
            inputs:
              awsCredentials: ${{ parameters.awsCredentials }}
              regionName: ${{ parameters.regionName }}
              awsCommand: 'sts'
              awsSubCommand: 'get-caller-identity'

      - deployment: Deployment
        displayName: Deployment
        environment: ${{ parameters.environment }}
        dependsOn: GetCallerIdentity
        strategy:
          runOnce:
            deploy:
              steps:
               - checkout: self

               - ${{ each item in parameters.manifests }}:
                 - task: Bash@3
                   name: ${{ format('Install{0}', item.name) }}
                   displayName: Install ${{ item.name }} provided manifests
                   inputs:
                     targetType: inline
                     script: |
                       kubectl apply -f ${{ item.manifest }}
        workspace:
          clean: all