parameters:
  - name: stageName
    type: string

  - name: dependsOn
    type: object
    default: []

  - name: environment
    type: string

  - name: kubernetesServiceConnection
    type: string

stages:
  - template: ../../azure-devops/stages/prepare-env.yml
    parameters:
      stageName: PrepareEnv
      dependsOn: ${{ parameters.dependsOn }}
      environment: ${{ parameters.environment }}
      
  - stage: ${{ parameters.stageName }}
    displayName: Deploy to EKS
    dependsOn: PrepareEnv
    jobs:  
      - deployment: DeployTest
        displayName: Deploy a test to EKS
        environment: $[ stageDependencies.PrepareEnv.CreateEnvironment.outputs['outputenv.environmentName'] ]
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: KubernetesManifest@1
                  displayName: Deploy to Kubernetes cluster test manifest
                  inputs:
                    action: deploy
                    kubernetesServiceConnection: ${{ parameters.kubernetesServiceConnection }}
                    namespace: nginx
                    manifests: |
                      $(System.DefaultWorkingDirectory)/terraform/aws/projects/eks-deployments/yamls/deployments/nginx/deployment.yml
