parameters:
  - name: stageName
    type: string

  - name: dependsOn
    type: object
    default: []

  - name: environment
    type: string
    default: 'eks-test'

  - name: kubernetesServiceConnection
    type: string

stages:
  - stage: CreatEnv
    displayName: Create environment
    dependsOn: ${{ parameters.dependsOn }}
    jobs:
      - job: CreateEnv
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: azure-connector
              scriptType: bash
              inlineScript: |
                az pipelines environment create \
                  --name ${{ parameters.environment }} \
                  --resource-type "none" \
                  --organization "$(System.TeamFoundationCollectionUri)" \
                  --project "$(System.TeamProject)"

  - stage: ${{ parameters.stageName }}
    displayName: Deploy to EKS
    dependsOn: CreatEnv
    jobs:  
      - deployment: DeployTest
        displayName: Deploy a test to EKS
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: KubernetesManifest@1
                  displayName: Deploy to Kubernetes cluster test manifest
                  inputs:
                    action: deploy
                    kubernetesServiceConnection: ${{ parameters.kubernetesServiceConnection }}
                    namespace: nginx
                    manifests: |
                      $(System.DefaultWorkingDirectory)/terraform/aws/projects/eks-deployments/yamls/deployments/nginx/deployment.yml
