parameters:
  - name: stageName
    type: string

  - name: dependsOn
    type: object
    default: []

  - name: environment
    type: string

  - name: regionName
    type: string

  - name: awsCredentials
    type: string
  
  - name: awsAccountId
    type: string

  - name: clusterName
    type: string

  - name: manifests
    type: object
    default: []

stages:
  - stage: Deploy
    displayName: Deploy k8s ${{ parameters.manifests.name }}
    dependsOn: ${{ parameters.dependsOn }}
    jobs:
      - deployment: Deployment
        displayName: Deployment
        environment: ${{ parameters.environment }}
        variables:
          roleArn: "arn:aws:iam::${{ parameters.awsAccountId }}:role/azdo-federation"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                
                - task: Bash@3
                  name: GetCallerIdentity
                  displayName: aws sts get-caller-identity
                  inputs:
                    targetType: inline
                    script: |
                      aws sts get-caller-identity

                - task: Bash@3
                  name: KubeUpdateConfig
                  displayName: kube update config
                  condition: succeeded()
                  inputs:
                    targetType: inline
                    script: |
                      aws eks update-kubeconfig \
                        --region ${{ parameters.regionName }} \
                        --name ${{ parameters.clusterName }}
                  
                - ${{ each item in parameters.manifests }}:
                  - task: Bash@3
                    name: ${{ format('Install{0}', item.name) }}
                    displayName: Install ${{ item.name }} provided manifests
                    inputs:
                      targetType: inline
                      script: |
                        kubectl apply -f ${{ item.manifest }}
        workspace:
          clean: all