parameters:
  - name: stageName
    type: string

  - name: dependsOn
    type: object
    default: []

  - name: environment
    type: string

  - name: kubernetesServiceConnection
    type: string

stages:
  - stage: DeployNamespace
    displayName: Deploy k8s namespace
    dependsOn: ${{ parameters.dependsOn }}
    jobs:
       - deployment: DeployPullRequest
         displayName: Deploy Pull request
         environment: ${{ parameters.environment }}
         strategy:
           runOnce:
             deploy:
               steps:
                - reviewApp: default
                
                - task: Kubernetes@1
                  displayName: 'Create a new namespace'
                  inputs:
                    command: apply
                    useConfigurationFile: true
                    inline: '{ "kind": "Namespace", "apiVersion": "v1", "metadata": { "name": "nginx"" }}'

  - stage: ${{ parameters.stageName }}
    displayName: Deploy to EKS
    dependsOn: PrepareEnv
    jobs:  
      - deployment: DeployTest
        displayName: Deploy a test to EKS
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: Kubernetes@1
                  displayName: Deploy to Kubernetes cluster test manifest
                  inputs:
                    command: apply
                    namespace: 'nginx'
                    useConfigurationFile: true
                    inline: -f $(System.DefaultWorkingDirectory)/terraform/aws/projects/eks-deployments/yamls/deployments/nginx/deployment.yml
