parameters:
  - name: stageName
    type: string

  - name: dependsOn
    type: object
    default: []

  - name: environment
    type: string

  - name: kubernetesServiceConnection
    type: string

stages:
  - stage: PrepareEnv
    displayName: Prepare DevOps Environment
    dependsOn: ${{ parameters.dependsOn }}
    jobs:
    - job: CreateEnvironment
      displayName: Create Azure DevOps Environment if missing
      steps:
        - checkout: none
        - script: |
            set -eux

            az extension add --name azure-devops || true
            az devops configure --defaults organization=https://dev.azure.com/$(System.CollectionId) project=$(System.TeamProject)
            EXISTING=$(az pipelines environment list --query "[?name=='${{ paramenters.environment }}'] | length(@)")
            if [ "$EXISTING" -eq 0 ]; then
              echo "Creating environment '${{ paramenters.environment }}'..."
              az pipelines environment create --name ${{ paramenters.environment }} --resource-type none
            else
              echo "Environment '${{ paramenters.environment }}' already exists"
            fi
          env:
            AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)


  - stage: ${{ parameters.stageName }}
    displayName: Deploy to EKS
    dependsOn: PrepareEnv
    jobs:  
      - deployment: DeployTest
        displayName: Deploy a test to EKS
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: KubernetesManifest@1
                  displayName: Deploy to Kubernetes cluster test manifest
                  inputs:
                    action: deploy
                    kubernetesServiceConnection: ${{ parameters.kubernetesServiceConnection }}
                    namespace: nginx
                    manifests: |
                      $(System.DefaultWorkingDirectory)/terraform/aws/projects/eks-deployments/yamls/deployments/nginx/deployment.yml
