groups:
  - name: node_exporter_alert
    rules:
      - record: job_instance_mode:node_cpu_seconds:avg_rate5m
        expr: avg by (job, instance, mode) (rate(node_cpu_seconds_total[5m]))
  
      - alert: InstanceDown
        expr: up == 0
        for: 5s