{{- if .Values.service -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.app.name }}
  annotations:
    {{- include "service.metadata.annotations.lb" . | nindent 4 }}
    {{- include "service.metadata.annotations.sg" . | nindent 4 }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - name: http
      port: {{ .Values.service.ports.port }}
      targetPort: {{ .Values.service.ports.targetPort }}
  type: {{ .Values.service.type }}
{{- end -}}