parameters:
  - name: dependsOn
    type: object
    default: []
  
  - name: stageName
    type: string
    default: ''

stages:
  - stage: ${{ parameters.stageName }}
    displayName: Delete AWS CLI v1
    dependsOn: 
      - ${{ parameters.dependsOn }}
    jobs:
      - job: DeleteAWS
        displayName: Delete AWS CLI v1
        continueOnError: true
        steps:
          - checkout: none
          - task: Bash@3
            name: UninstallAWS
            displayName: Uninstall AWC CLI v1
            inputs:
              targetType: inline
              script: |
                sudo rm -rf /usr/local/aws
                sudo rm -rf /usr/local/bin/aws*
        workspace:
          clean: all