parameters:
  - name: jobAction
    type: string
    values:
      - Install
      - Uninstall

jobs:
  - ${{ if eq(parameters.jobAction, "Install") }}:
    - job: ${{ format('{0}AWS', parameters.jobAction }}
      displayName: Installing AWS
      steps:
        - task: Bash@3
          name: check
          displayName: Check if AWS CLI is installed already
          inputs:
            targetType: inline
            script: |
              if command -v aws >/dev/null 2>&1; then
                echo "AWS CLI found"
                echo "##vso[task.setvariable variable=installed]true"
              else
                echo "AWS CLI NOT found"
                echo "##vso[task.setvariable variable=installed]false"
              fi

        - task: Bash@3
          name: install
          displayName: Install AWS CLI v1
          condition: eq(variables.installed, 'false')
          inputs:
            targetType: inline
            script: |
              curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
              unzip awscli-bundle.zip
              sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
              rm -r awscli-bundle

        - task: Bash@3
          name: verify
          condition: eq(variables.installed, 'true')
          displayName: Verify AWS CLI version
          inputs:
            targetType: inline
            script: aws --version

  - ${{ if eq(parameters.jobAction, "Uninstall") }}:
    - job: ${{ format('{0}AWS', parameters.jobName }}
      displayName: Uninstalling AWS
      steps:
        - task: Bash@3
          name: uninstall
          displayName: Uninstall AWS
          inputs:
            targetType: inline
            script: |
              sudo rm -rf /usr/local/aws
              sudo rm -rf /usr/local/bin/aws*