adminPassword: grafana

ingress:
  enabled: true
  ingressClassName: nginx
  hosts: 
    - grafana.mishap.local
  annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  path: /
  extraPaths:
    - path: /
      pathType: Prefix
      backend:
        service:
          name: grafana
          port:
            number: 80



# --- Don’t try to chown as root; your EmptyDir doesn't need it ---
# initChownData:
#  enabled: false
