adminPassword: admin

ingress:
  enabled: true
  ingressClassName: alb
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  path: /
  extraPaths:
    - path: /
      pathType: Prefix
      backend:
        service:
          name: grafana
          port:
            number: 80
