parameters:
  - name: k8sVersion
    type: string

stages:
  - stage: InstallKubectl
    displayName: Install kubectl
    jobs:
      - job: DetectArch
        displayName: Detect Linux Arch
        steps:
          - checkout: none

          - bash: |
              ARCH=$(uname -m)
              case $ARCH in
                x86_64) KUBECTL_ARCH="amd64" ;;
                aarch64) KUBECTL_ARCH="arm64" ;;
                *) echo "Unsupported architecture: $ARCH"; exit 1 ;;
              esac
              echo "##vso[task.setvariable variable=kubectl_arch;isOutput=true]${KUBECTL_ARCH}"
            name: detect
      
      - job: InstallKubectl
        displayName: Install kubectl
        dependsOn: DetectArch
        steps:
          - checkout: none

          - ${{ if eq(parameters.k8sVersion, '') }}:
            - task: Bash@3
              name: InstallKubectlLatest
              displayName: Install latest kubectl
              variables:
                kubectl_arch: $[ dependencies.DetectArch.outputs['detect.kubectl_arch'] ]
              inputs:
                targetType: inline
                script: |
                  echo "Detected architecture: $(kubectl_arch)"
                  KUBE_VER=$(curl -L -s https://dl.k8s.io/release/stable.txt)
                  echo "Installing kubectl version $KUBE_VER"
                  curl -LO "https://dl.k8s.io/release/${KUBE_VER}/bin/linux/$(kubectl_arch)/kubectl"
                  chmod +x kubectl && sudo mv kubectl /usr/local/bin/

          - ${{ if ne(parameters.k8sVersion, '') }}:
            - task: Bash@3
              name: InstallKubectlv${{ parameters.k8sVersion }}
              displayName: Install kubectl v${{ parameters.k8sVersion }}
              variables:
                kubectl_arch: $[ dependencies.DetectArch.outputs['detect.kubectl_arch'] ]
              inputs:
                targetType: inline
                script: |
                  echo "Detected architecture: $(kubectl_arch)"
                  KUBE_VER="v${{ parameters.k8sVersion }}"
                  echo "Installing kubectl version $KUBE_VER"
                  curl -LO "https://dl.k8s.io/release/${KUBE_VER}/bin/linux/$(kubectl_arch)/kubectl"
                  chmod +x kubectl && sudo mv kubectl /usr/local/bin/