parameters:
  - name: deploymentName
    type: string
  - name: dependsOn
    type: object
    default: []
  - name: environment
    type: string
  - name: awsCredentials
    type: string
  - name: awsRegion
    type: string
    default: us-east-1
  - name: awsClusterName
    type: string
  - name: manifests
    type: object
    default: []

jobs:
  - deployment: ${{ parameters.deploymentName }}
    displayName: ${{ parameters.deploymentName }}
    dependsOn: ${{ parameters.dependsOn }}
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: AWSCLI@1
              name: aws_sts_get_caller_identity
              displayName: aws sts get-caller-identity
              inputs:
                awsCredentials: ${{ parameters.awsCredentials }}
                regionName: ${{ parameters.awsRegion }}
                awsCommand: sts
                awsSubCommand: get-caller-identity

            - task: Bash@3
              name: update_config
              displayName: aws eks update-kubeconfig
              condition: succeeded()
              inputs:
                targetType: inline
                script: |
                  aws eks update-kubeconfig \
                    --region ${{ parameters.awsRegion }} \
                    --name ${{ parameters.awsClusterName }}
                  
            - task: Bash@3
              name: copy_sg_ids
              displayName: copy security groups ids
              condition: succeeded()
              inputs:
                targetType: inline
                script: |
                  cd terraform/aws/projects/eks-automode;
                  terraform output -raw eks_sg_ids | tr -d '[]" ' | tr ',' '\n' > .sg-ids.output
                  mv .sg-ids.output $(System.DefaultWorkingDirectory)/kubernetes/helm/local-business/

            # - ${{ if gt(length(parameters.manifests), 0) }}:
              # - ${{ each item in parameters.manifests }}:
                # - task: Bash@3
                  # name: ${{ format('apply_{0}', item.name) }}
                  # displayName: apply ${{ item.name }} in ${{ parameters.awsClusterName }} cluster 
                  # inputs:
                    # targetType: inline
                    # script: |
                      # kubectl apply -f ${{ item.manifest }}
    workspace:
      clean: all