parameters:
  - name: deploymentName
    type: string
  - name: dependsOn
    type: object
    default: []
  - name: environment
    type: string
  - name: awsRegion
    type: string
    default: us-east-1
  - name: clusterName
    type: string
  - name: manifests
    type: object
    default: []

jobs:
  - deployment: ${{ parameters.deploymentName }}
    displayName: Deployment
    dependsOn: ${{ parameters.dependsOn }}
    environment: ${{ parameters.environment }}
    variables:
      roleArn: "arn:aws:iam::${{ parameters.awsAccountId }}:role/azdo-federation"
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            
            # - task: AWSCLI@1
              # name: AWSCLIGetIdentity
              # displayName: Testing AWSCLI task
              # inputs:
                # awsCredentials: ${{ parameters.awsCredentials }}
                # regionName: ${{ parameters.awsRegion }}
                # awsCommand: sts
                # awsSubCommand: get-caller-identity

            - task: Bash@3
              name: KubeUpdateConfig
              displayName: aws eks update-kubeconfig
              condition: succeeded()
              inputs:
                targetType: inline
                script: |
                  aws eks update-kubeconfig \
                    --region ${{ parameters.awsRegion }} \
                    --name ${{ parameters.clusterName }}
              
            - ${{ each item in parameters.manifests }}:
              - task: Bash@3
                name: ${{ format('Install{0}', item.name) }}
                displayName: Install ${{ item.name }} provided manifests
                inputs:
                  targetType: inline
                  script: |
                    kubectl apply -f ${{ item.manifest }}
    workspace:
      clean: all