parameters:
  - name: projectRoot
    type: string
    default: $( System.DefaultWorkingDirectory )

  - name: azureServiceConnectorId
    type: string
    default: $( azureServiceConnectorId )

  - name: apps
    type: object
    default: []

  - name: pythonVersion
    type: string
    default: "3.13"

steps:
- bash: |
    touch .env
  name: CreateEnvFile
  displayName: "Create .env file"
  workingDirectory: ${{ parameters.projectRoot }}/app

- bash: |
    echo "APP_ENV=$(APP_ENV)" >> ./.env
    echo "X_RAPIDAPI_KEY=$(X_RAPIDAPI_KEY)" >> ./.env
  name: SaveEnvVaribalesInFile
  displayName: "Save env varibales in .env"
  workingDirectory: ${{ parameters.projectRoot }}/app

- bash: |
    python -m venv antenv
    source antenv/bin/activate
    pip install --no-cache-dir -r requirements.txt
  name: InstallDependencies
  displayName: "Install Python dependencies"
  workingDirectory: ${{ parameters.projectRoot }}/app

- task: ArchiveFiles@2
  name: ZipFiles
  displayName: "Archive Python App"
  inputs:
    rootFolderOrFile: 'app'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$( Build.ArtifactStagingDirectory )/app.zip'
    replaceExistingArchive: true
  
- ${{ each app in parameters.apps }}:
  - task: AzureWebApp@1
    name: AzureWebApp_${{ replace(app.name, '-', '_') }}
    displayName: "Deploy to ${{ app.name }}"
    inputs:
      azureSubscription: "${{ azureServiceConnectorId }}"
      appName: "${{ app.name }}"
      appType: "${{ app.type }}"
      resourceGroupName: ${{ app.resourceGroup }}
      package: "$(Build.ArtifactStagingDirectory)/app.zip"
      runtimeStack: "PYTHON|${{ parameters.pythonVersion }}"
      startUpCommand: "python app.py"
    env:
      SCM_DO_BUILD_DURING_DEPLOYMENT: true
      APP_ENV: $( APP_ENV )
      X_RAPIDAPI_KEY: $( X_RAPIDAPI_KEY )