parameters:
  - name: azureServiceConnectorId
    type: string
    default: $( azureServiceConnectorId )

steps:
- task: AzureCLI@2
  name: GetAppDataTask
  displayName: "Get App Services names"
  inputs:
    scriptType: bash
    scriptLocation: inlineScript
    azureSubscription: "${{ parameters.azureServiceConnectorId }}"
    inlineScript: |
      apps=$(az webapp list --query "[].{name:name, type:kind, resourceGroup:resourceGroup}" -o json)

      # Process and compact the JSON for use as pipeline output
      compacted=$(echo "$apps" | jq -c '[.[] | {name, type: (if .type | contains("linux") then "webAppLinux" else "webApp" end), resourceGroup}]')

      echo "Compact JSON: $compacted"

      # Set output variable
      echo "##vso[task.setVariable variable=apps;isOutput=true]$compacted"
