parameters:
  - name: azureServiceConnectorId
    type: string
    default: $( azureServiceConnectorId )

steps:
- task: AzureCLI@2
  name: GetAppDataTask
  displayName: "Get App Services names"
  inputs:
    scriptType: bash
    scriptLocation: inlineScript
    azureSubscription: "$( azureServiceConnectorId )"
    inlineScript: |
      apps=$(az webapp list --query "[].{name:name}" -o json)

- script: |
    echo "$[ 'GetAppDataTask.apps' ]" | jq '[.[] | {name, type: (if .type | contains("linux") then "webAppLinux" else "webApp" end), resourceGroup}]' | jq .
    echo "##vso[task.setVariable variable=apps;isOutput=true]$parsed_apps"
  name: SetAppsAsVariable
  displayName: "Store apps data in a variable"
