name: 'eks-$(Build.SourceBranch)-$(Date:yyyy-MM-dd)$(Rev:.r)'

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - azure-pipelines/eks.yml
      - azure-pipelines/templates/aws/stages/*

resources:
  webhooks:
    - webhook: TerraformApplied
      connection: TerraformAppliedServiceConnection

pool:
  name: 'Local'

variables:
  - name: installAWS
    value: true

  - name: projectRoot
    value: $(System.DefaultWorkingDirectory)

  - name: awsCredentials
    value: aws-oidc-federation

  - name: regionName
    value: us-east-1 
  
  - name: clusterName
    value: terraform-test

stages:
  - template: ./templates/aws/stages/install-aws.yml
    parameters:
      stageName: InstallAWSCLIv1
      installAWS: ${{ variables.installAWS }}
      awsCredentials: $(awsCredentials)
  
  - template: ./templates/aws/stages/connect-to-eks.yml
    parameters:
      stageName: GetEKSClusterInfo
      dependsOn:  InstallAWSCLIv1
      awsCredentials: $(awsCredentials)
      regionName: $(regionName)
      clusterName: $(clusterName)
  
  - template: ./templates/kubernetes/stages/deploy-to-cluster.yml
    parameters:
      stageName: DeployToEKS
      dependsOn: GetEKSClusterInfo
      kubernetesServiceConnection: $(awsCredentials)
              
  # - template: ./templates/aws/stages/delete-aws.yml 
    # parameters: 
      # dependsOn: GetEKSClusterInfo
      # stageName: DeleteAWSCLIv1