name: 'eks-$(Date:yyyy-MM-dd)$(Rev:.r)'

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - azure-pipelines/eks.yml

pool:
  name: 'Local'

variables:
  - name: projectRoot
    value: $(System.DefaultWorkingDirectory)

stages:
  - stage: EchoJobRoot
    displayName: Show job root
    jobs:
      - job: Deploy
        workspace:
          clean: all
        displayName: Deploy Application
        steps:
        
        - task: Bash@3
          displayName: 'Debug — Show current dir'        
          inputs:
            targetType: inline
            script: |
              echo 'Working directory from variables: ${pwd}'
              pwd
          continueOnError: true

        - task: Bash@3
          displayName: 'Install AWS CLI'
          inputs:
            targetType: inline
            script: |
              ls -lh .
              curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
              ls -lh
              unzip awscli-bundle.zip
              ls -lh
              sudo ./awscli-bundle/install 
              # -i /usr/local/aws -b /usr/local/bin/aws
              sudo chown root:wheel /root/.local/lib/aws/bin/aws
              /root/.local/lib/aws/bin/aws --version
              
            # workingDirectory: $(projectRoot)

        - script: |
            export PATH=/root/.local/lib/aws/bin/:$PATH
            aws --version
        # - script: |
            # curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
        # - script: 
            # ls -lh .
        
        - task: Bash@3
          displayName: 'Debug — Show working dir'        
          inputs:
            targetType: inline
            script: |
              echo 'Working directory from variables: $(projectRoot)'
              ls -lh .
              ls -lh /usr/local/bin/aws
              aws --version
          continueOnError: true
        
        - task: AWSCLI@1
          displayName: 'AWSCLI@1 version check'
          inputs:
            awsCommand: aws
            awsSubCommand: --version